// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwmO1Lk-rnzsmSRX-SP7cKu68CJJVTYpg',
    appId: '1:416690321865:web:489c315c1a90c9a2e41018',
    messagingSenderId: '416690321865',
    projectId: 'testdriveapp-c2cdf',
    authDomain: 'testdriveapp-c2cdf.firebaseapp.com',
    storageBucket: 'testdriveapp-c2cdf.appspot.com',
    measurementId: 'G-VXKGV4CJY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiVjG1rl4m3S_hDZclbd79jpj63AI0_w8',
    appId: '1:416690321865:android:7dc77fdcd308ec59e41018',
    messagingSenderId: '416690321865',
    projectId: 'testdriveapp-c2cdf',
    storageBucket: 'testdriveapp-c2cdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcf2d58KjDI3jJEMemLk9avCORydnWiGo',
    appId: '1:416690321865:ios:0583c3864d12f7b1e41018',
    messagingSenderId: '416690321865',
    projectId: 'testdriveapp-c2cdf',
    storageBucket: 'testdriveapp-c2cdf.appspot.com',
    iosBundleId: 'com.example.driveTestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcf2d58KjDI3jJEMemLk9avCORydnWiGo',
    appId: '1:416690321865:ios:cf5d51ef4b625d71e41018',
    messagingSenderId: '416690321865',
    projectId: 'testdriveapp-c2cdf',
    storageBucket: 'testdriveapp-c2cdf.appspot.com',
    iosBundleId: 'com.example.driveTestapp.RunnerTests',
  );
}
